export type CityData = {
    name: string;
    slug: string;
    metaDescription?: string;
    heroText?: string;
    whyTitle?: string;
    whyText?: string;
    ctaTitle?: string;
};

export const cities: CityData[] = [
    {
        name: 'Stockholm',
        slug: 'stockholm',
        metaDescription: 'Professionell takrengöring i Stockholm och hela Storstockholm. Skydda ditt tak mot saltluft, fukt och algpåväxt. ROT-avdrag gäller – få en fri offert idag!',
        heroText: 'Stockholms unika skärgårdsklimat med salt havsluft och fuktiga höstar sätter hårda krav på tak och fasader. Vi hjälper villaägare i hela Storstockholm – från Nacka till Sollentuna – att skydda sina fastigheter med professionell takrengöring och algbehandling.',
        whyTitle: 'Varför behöver tak i Stockholm extra omvårdnad?',
        whyText: 'Stockholms läge vid Mälaren och Östersjön skapar ett fuktigt mikroklimat som gynnar tillväxt av mossa och alger på tak och fasader. Saltluften från skärgården påskyndar dessutom nedbrytningen av takpannor och betongytor. Under de kalla vintrarna fryser den fukt som mossa och lav binder mot takytan, vilket kan leda till frostsprängningar och kostsamma skador. En professionell taktvätt i kombination med en långtidsverkande algbehandling förlänger ditt taks livslängd avsevärt och bevarar fastighetens marknadsvärde i ett av Sveriges dyraste bostadsområden.',
        ctaTitle: 'Räkna ut pris för takrengöring i Stockholm',
    },
    {
        name: 'Göteborg',
        slug: 'goteborg',
        metaDescription: 'Takrengöring i Göteborg – skydda ditt tak mot västkustens regn och blåst. Professionell mossbehandling med ROT-avdrag. Boka en fri offert!',
        heroText: 'Göteborg är en av Sveriges regnigaste städer och västkustens hårda väder sliter hårt på tak och fasader. Vi erbjuder professionell takrengöring i hela Göteborgsområdet – från Hisingen till Mölndal – med metoder anpassade för det maritima klimatet.',
        whyTitle: 'Västkustens väder kräver regelbunden takvård',
        whyText: 'Göteborgs läge vid kusten innebär riklig nederbörd, kraftiga vindar och salt havsluft som konstant utsätter takpannor och fasadmaterial för påfrestningar. Den höga luftfuktigheten under stora delar av året skapar perfekta förhållanden för mossa, alger och lav att etablera sig på takytor. Om dessa får växa fritt binder de fukt som under frostperioder kan orsaka sprickor och strukturella skador. Genom regelbunden professionell takrengöring och en skyddande algbehandling kan du förlänga ditt taks livslängd med många år och undvika de betydande kostnaderna för ett tidigt takbyte.',
        ctaTitle: 'Vad kostar takrengöring i Göteborg?',
    },
    {
        name: 'Malmö',
        slug: 'malmo',
        metaDescription: 'Takrengöring i Malmö och hela Skåne. Skydda taket mot Öresunds fukt och vind. Miljövänlig behandling med ROT-avdrag. Fri offert!',
        heroText: 'Malmös närhet till Öresund och det skånska slättlandskapet gör att tak och fasader utsätts för konstant vind och fukt. Vi hjälper fastighetsägare i hela Malmöområdet – från Limhamn till Burlöv – med skonsam men effektiv takrengöring anpassad efter Skånes klimat.',
        whyTitle: 'Skånes milda vintrar förvärrar algproblemen',
        whyText: 'Till skillnad från norra Sverige har Malmö och Skåne milda, fuktiga vintrar med få riktigt kalla perioder. Det innebär att mossa och alger kan fortsätta växa nästan året runt istället för att bromsas av djup frost. Kombinerat med de starka vindarna från Öresund, som bär med sig salt och fukt, bryts takmaterial ner snabbare än i inlandsklimat. Regelbunden professionell takrengöring är därför särskilt viktig i Malmöregionen för att förhindra permanent skada på takpannor och betongtakstennar. Med vår miljövänliga algbehandling skapar vi ett långtidsskydd som håller ditt tak rent och friskt.',
        ctaTitle: 'Beräkna priset för takrengöring i Malmö',
    },
    {
        name: 'Uppsala',
        slug: 'uppsala',
        metaDescription: 'Professionell takrengöring i Uppsala. Skydda ditt tak mot Upplands kalla vintrar och fuktiga höstar. ROT-avdrag. Få prisförslag direkt!',
        heroText: 'Uppsala med sitt inlandsklimat och kalla vintrar ställer höga krav på takvård. Frysningar och töcykler sliter hårt på tak där mossa och fukt fått fäste. Vi erbjuder professionell takrengöring i hela Uppsala kommun – från Sävja till Storvreta.',
        whyTitle: 'Upplands inlandsklimat och frostrisken för ditt tak',
        whyText: 'Uppsalas inlandsklimat innebär kraftiga temperaturskillnader mellan sommar och vinter, med långa frostperioder som kan vara förödande för tak där mossa och fukt fått fäste. Fyrisåns närhet bidrar till lokalt förhöjd luftfuktighet, särskilt under hösten, vilket skapar gynnsamma förhållanden för algpåväxt. De täta temperaturväxlingarna kring nollpunkten under vår och höst – så kallade frostcykler – är särskilt skadliga och kan spräcka takpannor inifrån. Genom att avlägsna mossa och behandla ditt tak med ett långtidsverkande skydd minskar du risken för dessa frostskador drastiskt och förlänger takets livslängd.',
        ctaTitle: 'Vad kostar det att tvätta taket i Uppsala?',
    },
    {
        name: 'Västerås',
        slug: 'vasteras',
        metaDescription: 'Takrengöring i Västerås – skydda ditt tak mot Mälardalens fuktiga klimat. Professionell moss- och algborttagning med ROT-avdrag. Fri offert!',
        heroText: 'Västerås vid Mälaren har ett fuktigt inlandsklimat som gör tak extra utsatta för mossa och alger. Vi erbjuder professionell takrengöring i hela Västerås – från Skultuna till Barkarö – med metoder som skyddar ditt tak på lång sikt.',
        whyTitle: 'Mälardalens fuktiga klimat och ditt tak',
        whyText: 'Västerås läge vid Mälaren och i Mälardalen skapar ett fuktigt mikroklimat som är en idealisk grogrund för mossa, lav och alger på takytor. De långa, mörka höstarna och vintrarna med begränsad avdunstning gör att fukt stannar kvar längre på taket. Samtidigt innebär Mälardalens temperaturvariationer att frostcykler regelbundet utsätter takmaterialet för stress. Västerås har även perioder med kraftig nederbörd som ytterligare belastar skadade takpannor. En professionell takrengöring följd av en skyddande behandling är den mest kostnadseffektiva åtgärden för att undvika framtida reparationer och bevara husets värde.',
        ctaTitle: 'Räkna ut priset för takrengöring i Västerås',
    },
    {
        name: 'Örebro',
        slug: 'orebro',
        metaDescription: 'Takrengöring i Örebro – skydda ditt tak mot Närkeslätten fukt och mossa. Professionell algbehandling med ROT-avdrag. Fri offert!',
        heroText: 'Örebro, mitt i Närkeslätten och vid Hjälmaren, har ett fuktigt inlandsklimat som gynnar mossa och alger på tak. Vi erbjuder professionell takrengöring i hela Örebroregionen – från Kumla till Hallsberg – med skonsamma metoder som ger långvarigt skydd.',
        whyTitle: 'Närkesslättens fuktiga luft och ditt tak',
        whyText: 'Örebros läge vid Hjälmaren och på den flacka Närkeslätten skapar förhållanden med hög luftfuktighet, särskilt under höst och vår. Den fuktiga luften i kombination med milda höstar gör att mossa och alger trivs ovanligt bra på takytor i regionen. Under vintern binder den påväxt som etablerats fukt mot takpannorna, och de återkommande frostcyklerna kan spräcka och försvaga takmaterialet inifrån. En professionell takrengöring med efterföljande algbehandling är det mest effektiva sättet att skydda ditt tak och förlänga dess livslängd med många år.',
        ctaTitle: 'Vad kostar takrengöring i Örebro?',
    },
    {
        name: 'Linköping',
        slug: 'linkoping',
        metaDescription: 'Professionell takrengöring i Linköping. Skydda taket mot Östgötaslättens klimat. Moss- och algborttagning med ROT-avdrag. Fri offert!',
        heroText: 'Linköping på Östgötaslätten har ett kontinentalt klimat med kalla vintrar och varma, fuktiga somrar – perfekta förhållanden för algpåväxt på tak. Vi erbjuder takrengöring i hela Linköpingsområdet – från Ljungsbro till Vikingstad.',
        whyTitle: 'Östgötaslättens klimat kräver regelbunden takvård',
        whyText: 'Linköpings läge på Östgötaslätten innebär ett utpräglat inlandsklimat med stora temperaturskillnader mellan årstiderna. De varma, fuktiga somrarna skapar ideala förhållanden för alg- och mosspåväxt, medan de kalla vintrarna med återkommande frost gör att fukt som bundits av mossa expanderar och skadar takpannor. Stångåns närhet bidrar dessutom till lokalt förhöjd fuktighet. Regelbunden professionell takrengöring förhindrar att dessa naturliga processer förkortar ditt taks livslängd och sparar dig kostnaden för tidiga reparationer.',
        ctaTitle: 'Räkna ut priset för takrengöring i Linköping',
    },
    {
        name: 'Helsingborg',
        slug: 'helsingborg',
        metaDescription: 'Takrengöring i Helsingborg – skydda taket mot Öresunds salt och vind. Professionell mossbehandling med ROT-avdrag. Boka fri offert!',
        heroText: 'Helsingborg vid Öresunds smalaste punkt utsätts för kraftiga vindar och salt havsluft som påskyndar nedbrytningen av takmaterial. Vi erbjuder professionell takrengöring i hela Helsingborgsområdet – från Rydebäck till Ödåkra.',
        whyTitle: 'Öresunds salta vindar sliter på ditt tak',
        whyText: 'Helsingborgs exponerade läge vid Öresunds smalaste del innebär att tak och fasader konstant utsätts för kraftiga vindar som bär med sig salt och fukt. Saltet fräter på takpannor och betongytor, medan den höga luftfuktigheten gör att alger och mossa snabbt etablerar sig. Det milda skånska klimatet innebär dessutom att algpåväxt kan ske nästan hela året. Genom professionell takrengöring och en skyddande behandling neutraliserar du saltets och fuktens skadliga effekter och bevarar ditt taks struktur och utseende under lång tid.',
        ctaTitle: 'Beräkna priset för takrengöring i Helsingborg',
    },
    {
        name: 'Jönköping',
        slug: 'jonkoping',
        metaDescription: 'Takrengöring i Jönköping – skydda taket mot Vätterns fukt och Smålands skogsluft. Algbehandling med ROT-avdrag. Fri offert!',
        heroText: 'Jönköping vid södra Vätterns strand och omgivet av småländska skogar har ett fuktigt klimat som är perfekt för mossa och alger. Vi hjälper fastighetsägare i hela Jönköpingsområdet – från Huskvarna till Bankeryd – med effektiv takrengöring.',
        whyTitle: 'Vätterns fukt och Smålands skogar påverkar ditt tak',
        whyText: 'Jönköpings unika läge vid Vättern, en av Europas största sjöar, skapar ett lokalt klimat med hög luftfuktighet och milda temperaturskillnader nära stranden. De omgivande småländska skogarna bidrar ytterligare med fukt och organiskt material som hamnar på takytor. Denna kombination gör att mossa, lav och alger trivs ovanligt bra på tak i Jönköpingsregionen. Om påväxten inte avlägsnas regelbundet binder den vatten som vid frost kan orsaka allvarliga skador på takpannor och underliggande konstruktion. En professionell takrengöring är den smartaste investeringen för ditt hus.',
        ctaTitle: 'Vad kostar takrengöring i Jönköping?',
    },
    {
        name: 'Norrköping',
        slug: 'norrkoping',
        metaDescription: 'Professionell takrengöring i Norrköping. Skydda taket mot Bråvikens fukt och industristadens klimat. ROT-avdrag gäller. Fri offert!',
        heroText: 'Norrköping vid Bråvikens innersta del har ett fuktigt kustklimat som gör tak extra utsatta för mossa och alger. Vi erbjuder skonsam men effektiv takrengöring i hela Norrköping – från Åby till Krokek.',
        whyTitle: 'Bråvikens fuktiga klimat och ditt tak i Norrköping',
        whyText: 'Norrköpings läge vid Bråviken och Motala ström skapar ett fuktigt mikroklimat som gynnar tillväxt av mossa och alger på takytor. Stadens industrihistoria har dessutom lämnat efter sig luftpartiklar som kan påskynda nedbrytningen av takmaterial. De östgötska vintrarna med återkommande frostcykler förvärrar situationen när fukt som bundits i mosspåväxt fryser och expanderar. Professionell takrengöring kombinerat med en långtidsverkande algbehandling skyddar ditt tak mot dessa påfrestningar och förlänger dess livslängd avsevärt.',
        ctaTitle: 'Räkna ut priset för takrengöring i Norrköping',
    },
    {
        name: 'Lund',
        slug: 'lund',
        metaDescription: 'Takrengöring i Lund – skydda ditt tak mot Skånes milda, fuktiga klimat. Professionell algborttagning med ROT-avdrag. Fri offert!',
        heroText: 'Lund i hjärtat av Skåne har milda vintrar och fuktiga höstar som ger alger och mossa perfekta tillväxtförhållanden året runt. Vi erbjuder professionell takrengöring i hela Lundaområdet – från Dalby till Stångby.',
        whyTitle: 'Skånes milda klimat – en utmaning för ditt tak i Lund',
        whyText: 'Lunds läge på den bördiga skånska slätten innebär milda vintrar med sällan långvarig frost, vilket gör att alger och mossa kan växa nästan året om. Den höga luftfuktigheten, driven av närheten till både Öresund och det omgivande jordbrukslandskapet, skapar optimala förhållanden för biologisk påväxt på takytor. Till skillnad från nordligare städer där kyla bromsar tillväxten, behöver tak i Lund regelbunden professionell rengöring och förebyggande behandling för att bibehålla sin funktion och estetik. Vår skonsamma metod avlägsnar påväxten utan att skada takmaterialet.',
        ctaTitle: 'Beräkna priset för takrengöring i Lund',
    },
    {
        name: 'Umeå',
        slug: 'umea',
        metaDescription: 'Takrengöring i Umeå – skydda taket mot Norrlands hårda vintrar och fuktiga somrar. Professionell mossbehandling med ROT-avdrag. Fri offert!',
        heroText: 'Umeå i Norrland har extrema temperaturskillnader, tunga snölaster och korta men intensivt fuktiga somrar som alla sliter hårt på tak. Vi erbjuder professionell takrengöring i hela Umeåregionen – från Holmsund till Sävar.',
        whyTitle: 'Norrlands extremklimat ställer hårda krav på ditt tak',
        whyText: 'Umeås norrländska klimat innebär långa, kalla vintrar med tung snö och is som belastar takkonstruktioner, följt av korta men intensivt fuktiga somrar då mossa och alger snabbt etablerar sig. De extrema temperaturskillnaderna – från minus 30 på vintern till plus 25 på sommaren – utsätter takmaterialet för kraftig expansion och kontraktion. Ume älvs närhet bidrar till hög luftfuktighet som ytterligare gynnar biologisk påväxt. En professionell takrengöring på sensommaren, före den hårda vintern, är den bästa tidpunkten för att skydda ditt tak och undvika frostskador.',
        ctaTitle: 'Vad kostar takrengöring i Umeå?',
    },
    {
        name: 'Gävle',
        slug: 'gavle',
        metaDescription: 'Professionell takrengöring i Gävle. Skydda taket mot Gävleborgs fuktiga kustklimat. Algbehandling med ROT-avdrag. Fri offert!',
        heroText: 'Gävle vid Bottenhavet har ett fuktigt kustklimat med kalla vintrar och korta somrar som skapar tuffa förhållanden för tak. Vi erbjuder takrengöring i hela Gävleområdet – från Valbo till Hille – med metoder anpassade för norrlandskusten.',
        whyTitle: 'Bottenhavets fukt och Gävles vintrar utmanar ditt tak',
        whyText: 'Gävles läge vid Bottenhavet och Gavleåns mynning skapar ett fuktigt kustklimat med långa, kalla vintrar. Den fuktiga havsluften i kombination med regn och snö gör att mossa och alger snabbt etablerar sig på takytor under de ljusa sommarmånaderna. När vintern sedan kommer fryser den fukt som påväxten binder, och de kraftiga snölasterna belastar redan försvagat takmaterial ytterligare. En professionell takrengöring i rätt tid på året – helst före vintern – är avgörande för att skydda ditt tak i Gävleregionen och undvika kostsamma reparationer.',
        ctaTitle: 'Räkna ut priset för takrengöring i Gävle',
    },
    {
        name: 'Borås',
        slug: 'boras',
        metaDescription: 'Takrengöring i Borås – Sveriges regnigaste stad. Skydda taket mot fukt och mossa. Professionell algbehandling med ROT-avdrag. Fri offert!',
        heroText: 'Borås är en av Sveriges regnigaste städer och den ständiga fukten gör tak extra utsatta för mossa och algpåväxt. Vi erbjuder professionell takrengöring i hela Boråsområdet – från Fristad till Dalsjöfors.',
        whyTitle: 'Sveriges regnigaste stad kräver extra takvård',
        whyText: 'Borås är känt som en av Sveriges allra regnigaste städer och det är inte utan anledning – stadens läge vid Sjuhäradsbygden fångar in fuktig luft från västkusten. Den rikliga nederbörden och den konstant höga luftfuktigheten skapar idealiska förhållanden för mossa, alger och lav att snabbt breda ut sig på takytor. I Borås behöver tak oftare professionell rengöring än i de flesta andra svenska städer, just på grund av den extrema fukten. Vår behandling avlägsnar inte bara befintlig påväxt utan ger även ett långtidsverkande skydd som är särskilt värdefullt i Borås unika klimat.',
        ctaTitle: 'Vad kostar takrengöring i Borås?',
    },
    {
        name: 'Eskilstuna',
        slug: 'eskilstuna',
        metaDescription: 'Takrengöring i Eskilstuna – skydda taket mot Mälardalens fukt. Professionell moss- och algborttagning med ROT-avdrag. Fri offert!',
        heroText: 'Eskilstuna i Mälardalen har ett fuktigt inlandsklimat med kalla vintrar som sliter på tak där mossa fått fäste. Vi erbjuder professionell takrengöring i hela Eskilstunaområdet – från Torshälla till Hällbybrunn.',
        whyTitle: 'Mälardalens klimat och takvård i Eskilstuna',
        whyText: 'Eskilstunas läge i Mälardalen, vid Eskilstunaån som rinner ut i Mälaren, ger staden ett fuktigt inlandsklimat. Närheten till vattendrag ökar luftfuktigheten lokalt och skapar gynnsamma förhållanden för biologisk påväxt på takytor. De kalla vintrarna med regelbundna frostcykler innebär att fukt i mosspåväxt fryser och expanderar, vilket gradvis försvagar takpannor och fogar. Sommartid accelererar de varma, fuktiga förhållandena tillväxten. En professionell takrengöring med skyddande behandling är den mest lönsamma åtgärden för att bevara ditt tak och undvika ett dyrt takbyte.',
        ctaTitle: 'Beräkna priset för takrengöring i Eskilstuna',
    },
    {
        name: 'Södertälje',
        slug: 'sodertalje',
        metaDescription: 'Takrengöring i Södertälje – skydda taket mot Mälarens fukt och Östersjöns påverkan. Algbehandling med ROT-avdrag. Fri offert!',
        heroText: 'Södertälje vid Mälaren och nära Östersjön har ett fuktigt klimat som gör tak extra utsatta för alger och mossa. Vi erbjuder professionell takrengöring i hela Södertäljeområdet – från Järna till Enhörna.',
        whyTitle: 'Dubbelexponering mot Mälaren och Östersjön',
        whyText: 'Södertäljes unika geografiska läge – vid Södertälje kanal som förbinder Mälaren med Östersjön – innebär en dubbel fuktexponering som få andra svenska städer upplever. Den fuktiga luften från båda vattendragen skapar perfekta villkor för mossa och algpåväxt på tak året runt. Södertäljes topografi med kullar och dalar kan dessutom skapa områden där fukt och dimma ligger kvar längre, vilket ytterligare förvärrar mossproblemen. Professionell takrengöring med en skyddande efterbehandling är särskilt viktig i denna region för att motverka den konstanta fuktpåverkan.',
        ctaTitle: 'Vad kostar takrengöring i Södertälje?',
    },
    {
        name: 'Karlstad',
        slug: 'karlstad',
        metaDescription: 'Professionell takrengöring i Karlstad. Skydda taket mot Vänerns fukt och Värmlands klimat. Algbehandling med ROT-avdrag. Fri offert!',
        heroText: 'Karlstad vid Vänern, Nordens största sjö, har ett fuktigt klimat med riklig nederbörd som gör tak extra utsatta. Vi erbjuder professionell takrengöring i hela Karlstadsområdet – från Skåre till Skattkärr.',
        whyTitle: 'Vänerns fukt och Värmlands nederbörd utmanar ditt tak',
        whyText: 'Karlstads läge vid Klarälvens delta, där älven rinner ut i Vänern, skapar ett lokalt klimat med hög luftfuktighet och riklig nederbörd. Vänern – Nordens största sjö – modererar temperaturen men bidrar samtidigt till en konstant fuktmättad luft som gynnar biologisk påväxt på takytor. Värmlands rika nederbördsmönster med långa regnperioder under hösten gör att mossa och alger snabbt sprider sig. Under vintern kan de kraftiga snölasterna och frostcyklerna samverka med mosspåväxt och orsaka strukturella skador. En årlig professionell takrengöring är avgörande för ditt taks hälsa i Karlstad.',
        ctaTitle: 'Räkna ut priset för takrengöring i Karlstad',
    },
    {
        name: 'Täby',
        slug: 'taby',
        metaDescription: 'Takrengöring i Täby – skydda villatakfaket mot Stockholms fuktiga klimat. Professionell mossbehandling med ROT-avdrag. Fri offert!',
        heroText: 'Täby norr om Stockholm är en utpräglad villakommun där de gröna omgivningarna och det fuktiga klimatet gör att tak snabbt drabbas av mossa och alger. Vi erbjuder professionell takrengöring i hela Täby – från Gribbylund till Arninge.',
        whyTitle: 'Villatäta Täby och utmaningen med mosspåväxt',
        whyText: 'Täby kommun, med sina många villor omgivna av grönska och skog, har unika förutsättningar för mosspåväxt på tak. De täta trädkronorna skapar skuggiga miljöer där fukt stannar kvar längre, och det organiska materialet från löv och barr som samlas på taket ger näring åt mossa och alger. Stockholmsregionens fuktiga höstar och kalla vintrar förvärrar problematiken – mossa binder vatten som vid frost spräcker takpannor. I en kommun med höga fastighetsvärden är regelbunden professionell takrengöring en klok investering som skyddar både takets funktion och hemmets marknadsvärde.',
        ctaTitle: 'Vad kostar takrengöring i Täby?',
    },
    {
        name: 'Växjö',
        slug: 'vaxjo',
        metaDescription: 'Takrengöring i Växjö – skydda taket mot Smålands sjörika och fuktiga klimat. Professionell algbehandling med ROT-avdrag. Fri offert!',
        heroText: 'Växjö, omgivet av småländska sjöar och skogar, har ett fuktigt klimat som gör tak extra utsatta för mossa och alger. Vi erbjuder professionell takrengöring i hela Växjöområdet – från Rottne till Gemla.',
        whyTitle: 'Smålands sjöar och skogar påverkar ditt tak i Växjö',
        whyText: 'Växjös läge mitt i det småländska sjölandet, omgivet av Växjösjön, Trummen och Helgasjön, skapar ett konstant fuktigt mikroklimat. Den omgivande barr- och lövskogen bidrar ytterligare med fukt och organiska partiklar som landar på takytor och ger näring åt mossa och alger. Smålands inlandsklimat med kalla vintrar innebär att fukt som bundits i påväxten fryser och orsakar frostskador på takpannor. Professionell takrengöring är särskilt viktigt i Växjö för att motverka den konstanta fuktpåverkan från de omgivande sjöarna och skogarna.',
        ctaTitle: 'Beräkna priset för takrengöring i Växjö',
    },
    {
        name: 'Halmstad',
        slug: 'halmstad',
        metaDescription: 'Takrengöring i Halmstad – skydda taket mot västkustens salt, vind och fukt. Professionell mossbehandling med ROT-avdrag. Fri offert!',
        heroText: 'Halmstad vid Hallandskusten utsätts för västkustens hårda väder med salt havsluft och riklig nederbörd. Vi erbjuder professionell takrengöring i hela Halmstadsområdet – från Getinge till Haverdal.',
        whyTitle: 'Hallandskustens väder kräver regelbunden takvård',
        whyText: 'Halmstads läge vid Nissan och Hallandskusten innebär att tak ständigt utsätts för västkustens fuktiga väder, salthaltiga havsvind och riklig nederbörd. Den milda halländska vintern gör att alger och mossa kan fortsätta växa under stora delar av året, medan de salta vindarna från Kattegatt påskyndar nedbrytningen av takmaterial. Kombinationen av salt, fukt och biologisk påväxt skapar en trippel belastning på taket som kräver regelbunden professionell rengöring. Vår behandling avlägsnar skadlig påväxt och ger ett skyddande lager som motstår västkustens hårda förhållanden.',
        ctaTitle: 'Vad kostar takrengöring i Halmstad?',
    },
];

export function getCityBySlug(slug: string): CityData | undefined {
    return cities.find(city => city.slug === slug);
}

